# This file shows all settings which the sdk uses.

# DO NOT make a copy of this file as the basis of your config. Some values are intentionally bogus
# as there's no sane default to set them to (e.g. virtual function indexes), and will likely cause
# crashes if used.

# You are not expected to provide all settings, you should only set those you need. Some settings
# will change behaviour simply by being defined. For example, if `uproperty_size` is set, the sdk
# will not attempt to auto detect it, and will instead assume the provided value is accurate.

# Not all settings are used under all build configurations - for example UE3 doesn't support FText,
# so `ftext_get_display_string_vf_index` is of course unused.

[unrealsdk]
# If true, creates an external console window mirroring what is written to the game's console.
# Always enabled in debug builds.
external_console = false

# The file to write log messages to, relative to the dll.
log_file = "unrealsdk.log"
# Changes the default logging level used in the unreal console.
console_log_level = "INFO"

# If set, overrides the executable name used for game detection in the shared module.
exe_override = ""

# Changes the size the `UProperty` class is assumed to have.
uproperty_size = -1
# Changes the size the `UStruct` class is assumed to have.
ustruct_size = -1
# Changes the alignment used when calling the unreal memory allocation functions.
alloc_alignment = -1

# The default console key set when one is not already bound. If a key is already bound via standard
# unreal facilities, this is ignored.
console_key = "Tilde"
# Overrides the virtual function index used when hooking `UConsole::ConsoleCommand`.
uconsole_console_command_vf_index = -1
# Overrides the virtual function index used when calling `UConsole::OutputText`.
uconsole_output_text_vf_index = -1

# Overrides the virtual function index used when calling `TReferenceController::DestroyObject`.
treference_controller_destroy_obj_vf_index = -1
# Overrides the virtual function index used when calling `TReferenceController::~TReferenceController`.
treference_controller_destructor_vf_index = -1

# Overrides the virtual function index used when calling `FText::GetDisplayString`.
ftext_get_display_string_vf_index = -1

# If true, locks simultaneous unreal function calls from different threads. This lock is held both
# during hooks and when you manually call unreal functions.
# When true, if external code must take care with it's own locks. If external code attempts to
# acquire a lock inside a hook, while at the same time trying to call an unreal function on the
# thread which holds that lock, the system will deadlock.
locking_function_calls = false

# After enabling `unrealsdk::hook_manager::log_all_calls`, the file to calls are logged to.
log_all_calls_file = "unrealsdk.calls.tsv"
